export const GET_MAILS_LIST_PENDING = "GET_MAILS_LIST_PENDING";
export const GET_MAILS_LIST_SUCCESS = "GET_MAILS_LIST_SUCCESS";
export const GET_MAILS_LIST_FAILED = "GET_MAILS_LIST_FAILED";

export const GET_MAIL_PENDING = "GET_MAIL_PENDING";
export const GET_MAIL_SUCCESS = "GET_MAIL_SUCCESS";
export const GET_MAIL_FAILED = "GET_MAIL_FAILED";

export const CREATE_MAIL_PENDING = "CREATE_MAIL_PENDING";
export const CREATE_MAIL_SUCCESS = "CREATE_MAIL_SUCCESS";
export const CREATE_MAIL_FAILED = "CREATE_MAIL_FAILED";

export const UPDATE_MAIL_PENDING = "UPDATE_MAIL_PENDING";
export const UPDATE_MAIL_SUCCESS = "UPDATE_MAIL_SUCCESS";
export const UPDATE_MAIL_FAILED = "UPDATE_MAIL_FAILED";

export const DELETE_MAIL_PENDING = "DELETE_MAIL_PENDING";
export const DELETE_MAIL_SUCCESS = "DELETE_MAIL_SUCCESS";
export const DELETE_MAIL_FAILED = "DELETE_MAIL_FAILED";
